### get all songs
GET http://localhost:3000/songs

###

GET http://localhost:3000/songs/1

### create song
POST http://localhost:3000/songs
Content-Type: application/json

{ 
"title": "Lasting Loverssss",
"artists": ["Siagla"],
"releasedDate" : "2022-07-29 00:00:00",
"duration" :"02:34"
}

###
X-Http-Method-Override: 
PUT http://localhost:3000/songs/1

###

DELETE http://localhost:3000/songs/1


