### create User

POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
      "firstName" :"john",
      "lastName" :"david",
      "email": "peterpaul24@gmail.com",
      "password" : "Strongpassword12345!"
}



### login user
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
       "email": "peterpaul24@gmail.com",
      "password" : "Strongpassword12345!"
}     